<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">registerContentTypes</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkJdHJ5CgkJewoJCQlTdHJpbmcgcyA9IFN5c3RlbS5nZXRQcm9wZXJ0eSgidG4uZXhjZWwuY29u
dGVudHR5cGVzIiwgImFwcGxpY2F0aW9uL3ZuZC5tcy1leGNlbCIpOwoJCQlTdHJpbmdUb2tlbml6
ZXIgc3RyaW5ndG9rZW5pemVyID0gbmV3IFN0cmluZ1Rva2VuaXplcihzLCAiLCIpOwoJCQlTdHJp
bmcgYXNbXSA9IG5ldyBTdHJpbmdbc3RyaW5ndG9rZW5pemVyLmNvdW50VG9rZW5zKCldOwoJCQlp
bnQgaSA9IDA7CgkJCVN0cmluZ0J1ZmZlciBzdHJpbmdidWZmZXIgPSBuZXcgU3RyaW5nQnVmZmVy
KCk7CgkJCWZvcig7IHN0cmluZ3Rva2VuaXplci5oYXNNb3JlVG9rZW5zKCk7IHN0cmluZ2J1ZmZl
ci5hcHBlbmQoYXNbaSsrXSkpCgkJCXsKCQkJCWFzW2ldID0gc3RyaW5ndG9rZW5pemVyLm5leHRU
b2tlbigpOwoJCQkJaWYoaSA+IDApCgkJCQkJc3RyaW5nYnVmZmVyLmFwcGVuZCgiLCIpOwoJCQl9
CgoJCQlpZihhcyA9PSBudWxsIHx8IGFzLmxlbmd0aCA9PSAwKQoJCQkJcmV0dXJuOwoJCQlJRGF0
YSBpZGF0YTEgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKDEpOwoJCQlWYWx1ZXNFbXVsYXRvci5wdXQo
aWRhdGExLCAiY29udGVudFR5cGVzIiwgYXMpOwoJCQl0cnkKCQkJewoJCQkJU2VydmljZS5kb0lu
dm9rZSgiU2ltcGxlRXhjZWxGb3JUTi5zZXJ2ZXIubXNleGNlbCIsICJyZWdpc3RlckNvbnRlbnRI
YW5kbGVyIiwgaWRhdGExKTsKCQkJCVN5c3RlbUxvZzIubG9nKDYsICJSZWdpc3RyZWQgY29udGVu
dCB0eXBlIHswfSBmb3IgQ29udGVudEhhbmRsZXJfRXhjZWxGaWxlIiwgc3RyaW5nYnVmZmVyLnRv
U3RyaW5nKCkpOwoJCQl9CgkJCWNhdGNoKFVua25vd25TZXJ2aWNlRXhjZXB0aW9uIF9leCkKCQkJ
ewoJCQkJU3lzdGVtTG9nMi5sb2coNCwgIlVuYWJsZSB0byByZWdpc3RlciBjb250ZW50IHR5cGVz
IHdpdGggdGhlIE1TIEV4Y2VsIEZpbGUgQ29udGVudCBIYW5kbGVyLiIpOwoJCQl9CgkJfQoJCWNh
dGNoKFRocm93YWJsZSB0aHJvd2FibGUpCgkJewoJCQl0aHJvdyBuZXcgRVhNTEV4Y2VwdGlvbigi
U2ltcGxlRXhjZWxGb3JUTi50bi5kb2MuZXhjZWw6cmVnaXN0ZXJDb250ZW50VHlwZXMiLCB0aHJv
d2FibGUpOwoJCX0K</value>
</Values>
